site_name: ITSM365.Support 
theme:
  name: material # https://squidfunk.github.io/mkdocs-material/
  favicon: logo.png
  logo: logo_l.svg
  features:
    - navigation.path
    - navigation.indexes

extra_css:
    - stylesheets/material-styles.css

nav:
  - Быстрый старт: 
    - Quick_Start_00.md
    - Наполнение оргструктуры: Quick_Start_1.md
    - Настройка правил для расчета времени на решение заявок: Quick_Start_2.md
    - Настройка оповещений по email и уведомлений в интерфейсе: Quick_Start_3.md
    - Настройка регистрации заявок по почте: Quick_Start_4.md
    - Регистрация заявки: Quick_Start_5.md

plugins:
    - search:
        lang:
          - ru


